project_name: go-semver
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
    ignore:
      - goos: linux
        goarch: 386
    main: ./cmd/semver/main.go
    binary: semver
    ldflags:
      - -s -w -X sigs.k8s.io/release-utils/version.gitVersion={{.Version}} -X sigs.k8s.io/release-utils/version.gitCommit={{.Commit}} -X sigs.k8s.io/release-utils/version.buildDate={{.Date}} -X sigs.k8s.io/release-utils/version.gitTreeState=clean
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    description: A tool to manage semantic versioning of software
    maintainer: Brad Pinter <brad.pinter@gmail.com>
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    dependencies:
      - git
