project_name: go-semver

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

env:
  - COSIGN_EXPERIMENTAL=true

builds:
  - id: go-semver-build
    binary: semver
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - "386"
    ignore:
      - goos: linux
        goarch: "386"
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - "{{ .Env.LDFLAGS }}"

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
    wrap_in_directory: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    description: A tool to manage semantic versioning of software
    maintainer: Brad Pinter <brad.pinter@gmail.com>
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    dependencies:
      - git
